POST http://localhost:8080/admin/reset HTTP/1.1

###

POST http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
  "email": "saul@bettercall.com",
  "password": "123456"
}

### Login

POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
  "email": "saul@bettercall.com",
  "password": "123456"
}

###

POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiJjNDA4YWYxNC02N2NlLTQ2ZGQtYWM3MS0xYTIwN2NjNjcyZTciLCJleHAiOjE3Njg0MzQwMTQsImlhdCI6MTc2ODQzMDQxNH0.lm_ACmRZzQG-a21n8UY2_JRZUp0uBXIAezvh1BbHUZk

{
  "body": "Clearly his taste in women is the same as his taste in lawyers: only the very best... with just a right amount of dirty!"
}

###

POST http://localhost:8080/api/refresh HTTP/1.1
content-type: application/json
Authorization: Bearer 2234c9c6ca5da5ece44a0ffeee961bb4dccde806a44d3a6e6e50f5a8b94b6dd7

###

POST http://localhost:8080/api/revoke HTTP/1.1
content-type: application/json
Authorization: Bearer 2234c9c6ca5da5ece44a0ffeee961bb4dccde806a44d3a6e6e50f5a8b94b6dd7

###

POST http://localhost:8080/api/refresh HTTP/1.1
content-type: application/json
Authorization: Bearer 2234c9c6ca5da5ece44a0ffeee961bb4dccde806a44d3a6e6e50f5a8b94b6dd7