POST http://localhost:8080/admin/reset HTTP/1.1

###

POST http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
  "email": "saul@bettercall.com",
  "password": "123456"
}

###

POST http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
  "email": "mike@bettercall.com",
  "password": "98765"
}

###

POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
  "email": "saul@bettercall.com",
  "password": "123456"
}

###

POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
  "email": "mike@bettercall.com",
  "password": "98765"
}

###

POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIxNWNhNjQ1ZS00Zjk0LTQwMjQtYTUzOS04YWY5NWZlZDlkZjEiLCJleHAiOjE3NjgyODYzMzUsImlhdCI6MTc2ODI4MjczNX0.hJtWzklOQSXsS0wbubHe0Z2d5b6cnKqlIXY-NN-PJng

{
  "body": "Clearly his taste in women is the same as his taste in lawyers: only the very best... with just a right amount of dirty!"
}

###

POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiJjMWRlMWE5OC03ZjY2LTQzY2MtYTFiNi0xM2Y5ZjA1MzY2ZjAiLCJleHAiOjE3NjgyODYzNTUsImlhdCI6MTc2ODI4Mjc1NX0.XuuqEN8a2t7tBgcZRaIy7UJMYJJWpgA7_8cfxXaEZUs

{
  "body": "No more half-measures."
}

###